### ISSUE TITLE
User gets no Notification, if the Replacement of  Text fails

### ISSUE THREAD

**Issue by Ergel** [batzen/Batzendev.Tools#1]
You can reproduce it in the following way:

Precondition = Create txt file. Type some Text in the file. Make the file readonly

1)Start the Batzendev Tool
2) Type something, that can be found in the readonly document.
3) Type something to replace the text found

Open the document. The text is not replaced, because the file is readonly. And the user don#t get any message, that the text is not replaced.

**Comment by batzen** [comment]
There is a badge in the lower left corner of the application which shows a number.
If anything unusual occurs during search or replace the number there show the number of "issues".
I will try to improve the visual appearance of that badge to change it's color depending on the severity of the issue which occurred.

**Comment by Ergel** [comment]
Thank you very much, Bastian.
