### ISSUE TITLE
Löschen von Ordnerbäumen mit Dateien einbauen

### ISSUE THREAD

**Issue by Mortendo1978** [batzen/Batzendev.Tools#4]
Löschen von 1-20kb Dateien in einer tief verzweigten Ordnerstruktur dauert in Windows eine gefühlte Ewigkeit (vor allem wenn der Ordner im Netzwerk liegt)

Irgendwie müßte man das mal parallelisieren.
![grafik](https://user-images.githubusercontent.com/105503317/168306182-5430bdee-82a6-4e9f-81d7-1f753855b189.png)

Löschdauer in Windows: mehrere Minuten

**Comment by batzen** [comment]
Ist in Version 6 mit drin.
